"use client";
import {useState} from 'react';
type Emp={id:number;name:string;branch:string;days:number;gross:number;returns:number};
const initial=[{id:1,name:'Ahmed Hassan',branch:'Cairo Main',days:26,gross:42000,returns:1200},{id:2,name:'Mohamed Ali',branch:'Cairo Main',days:24,gross:38000,returns:800},{id:3,name:'Sara Ibrahim',branch:'Cairo Main',days:22,gross:31000,returns:500}];
export default function Dashboard(){
 const [tab,setTab]=useState('Dashboard'),[target,setTarget]=useState(120000),[employees,setEmployees]=useState<Emp[]>(initial);
 const totalDays=employees.reduce((s,e)=>s+e.days,0),alloc=(e:Emp)=>totalDays?target*e.days/totalDays:0,net=(e:Emp)=>e.gross-e.returns,total=employees.reduce((s,e)=>s+net(e),0);
 const ach=target?total/target*100:0;
 const update=(id:number,k:keyof Emp,v:string)=>setEmployees(x=>x.map(e=>e.id===id?{...e,[k]:k==='name'||k==='branch'?v:Number(v)}:e));
 const add=()=>setEmployees(x=>[...x,{id:Date.now(),name:'New Employee',branch:'Cairo Main',days:26,gross:0,returns:0}]);
 const remove=(id:number)=>setEmployees(x=>x.filter(e=>e.id!==id));
 const menu=['Dashboard','Branches','Employees','Daily Sales','Reports','Settings'];
 return <main className="app"><aside><div className="logo">Sales<span>Track</span><small>PRO</small></div><div className="user">👤 Super Administrator<br/><small>System Owner</small></div>{menu.map(m=><button key={m} className={tab===m?'nav active':'nav'} onClick={()=>setTab(m)}>{m}</button>)}<div className="sideFoot">© SalesTrack Online</div></aside>
 <section className="workspace"><header><div><h1>{tab}</h1><p>{tab==='Dashboard'?'Company-wide sales performance overview':`Manage ${tab.toLowerCase()} and system data`}</p></div><div className="headerActions"><button>🔔</button><button className="primary">September 2026</button></div></header>
 {tab==='Dashboard'&&<><div className="cards"><Card t="Branch Target" v={target.toLocaleString()}/><Card t="Net Sales" v={total.toLocaleString()}/><Card t="Achievement" v={ach.toFixed(1)+'%'}/><Card t="Remaining" v={Math.max(0,target-total).toLocaleString()}/></div>
 <div className="grid2"><div className="panel"><h3>Monthly Sales Progress</h3><div className="progress"><div style={{width:Math.min(100,ach)+'%'}}></div></div><strong>{ach.toFixed(1)}% achieved</strong><p>{total.toLocaleString()} of {target.toLocaleString()}</p></div><div className="panel"><h3>Branch Ranking</h3><Rank name="Cairo Main" value={ach}/><Rank name="Giza Branch" value={76}/><Rank name="Nasr City" value={63}/></div></div></>}
 {tab==='Branches'&&<Branches/>}
 {tab==='Employees'&&<div className="panel"><div className="panelHead"><div><h3>Employee & Target Management</h3><p>Targets are distributed automatically based on working days.</p></div><button className="primary" onClick={add}>+ Add Employee</button></div><div className="targetBox"><label>Branch Monthly Target</label><input type="number" value={target} onChange={e=>setTarget(Number(e.target.value||0))}/></div><Table employees={employees} update={update} remove={remove} alloc={alloc} net={net}/></div>}
 {tab==='Daily Sales'&&<Daily employees={employees} update={update} net={net}/>}
 {tab==='Reports'&&<Reports employees={employees} target={target} alloc={alloc} net={net}/>}
 {tab==='Settings'&&<Settings/>}
 </section></main>}
function Card({t,v}:{t:string,v:string}){return <div className="card"><span>{t}</span><strong>{v}</strong></div>}
function Rank({name,value}:{name:string,value:number}){return <div className="rank"><div><b>{name}</b><span>{value.toFixed(0)}%</span></div><div className="miniProgress"><i style={{width:value+'%'}}/></div></div>}
function Table({employees,update,remove,alloc,net}:any){return <div className="tableWrap"><table><thead><tr><th>Name</th><th>Branch</th><th>Working Days</th><th>Allocated Target</th><th>Gross Sales</th><th>Returns</th><th>Net Sales</th><th>Achievement</th><th/></tr></thead><tbody>{employees.map((e:any)=>{let a=alloc(e),p=a?net(e)/a*100:0;return <tr key={e.id}><td><input value={e.name} onChange={x=>update(e.id,'name',x.target.value)}/></td><td>{e.branch}</td><td><input type="number" value={e.days} onChange={x=>update(e.id,'days',x.target.value)}/></td><td>{a.toFixed(0)}</td><td>{e.gross.toLocaleString()}</td><td>{e.returns.toLocaleString()}</td><td>{net(e).toLocaleString()}</td><td className={p>=100?'good':'warn'}>{p.toFixed(1)}%</td><td><button className="danger" onClick={()=>remove(e.id)}>Remove</button></td></tr>})}</tbody></table></div>}
function Branches(){return <div className="panel"><div className="panelHead"><h3>Company Branches</h3><button className="primary">+ Add Branch</button></div><table><thead><tr><th>Branch</th><th>Code</th><th>Manager</th><th>Employees</th><th>Status</th></tr></thead><tbody><tr><td>Cairo Main</td><td>CAI-001</td><td>Ahmed Manager</td><td>3</td><td className="good">Active</td></tr><tr><td>Giza Branch</td><td>GIZ-001</td><td>Mohamed Manager</td><td>12</td><td className="good">Active</td></tr></tbody></table></div>}
function Daily({employees,update,net}:any){return <div className="panel"><div className="panelHead"><h3>Daily Sales Entry</h3><input className="date" type="date" defaultValue="2026-09-01"/></div><div className="tableWrap"><table><thead><tr><th>Employee</th><th>Gross Sales</th><th>Returns</th><th>Net Sales</th></tr></thead><tbody>{employees.map((e:any)=><tr key={e.id}><td>{e.name}</td><td><input type="number" value={e.gross} onChange={x=>update(e.id,'gross',x.target.value)}/></td><td><input type="number" value={e.returns} onChange={x=>update(e.id,'returns',x.target.value)}/></td><td>{net(e).toLocaleString()}</td></tr>)}</tbody></table></div><button className="primary save">Save Daily Sales</button></div>}
function Reports({employees,target,alloc,net}:any){let total=employees.reduce((s:any,e:any)=>s+net(e),0);return <><div className="cards"><Card t="Employees" v={String(employees.length)}/><Card t="Total Net Sales" v={total.toLocaleString()}/><Card t="Monthly Target" v={target.toLocaleString()}/><Card t="Average Achievement" v={(employees.reduce((s:any,e:any)=>s+(alloc(e)?net(e)/alloc(e)*100:0),0)/employees.length).toFixed(1)+'%'}/></div><div className="panel"><h3>Monthly Performance Report</h3><Table employees={employees} update={()=>{}} remove={()=>{}} alloc={alloc} net={net}/><button className="primary save">Export Report</button></div></>}
function Settings(){return <div className="grid2"><div className="panel"><h3>Company Settings</h3><label>Company Name</label><input defaultValue="SalesTrack Company"/><label>Currency</label><input defaultValue="EGP"/><button className="primary save">Save Settings</button></div><div className="panel"><h3>User Roles</h3><p>Super Admin — Full system access</p><p>Branch Manager — Branch management access</p><p>Employee — Personal sales access</p></div></div>}