'use client'

import { FormEvent, useEffect, useMemo, useState } from 'react'
import { Check, Copy, Gift, Loader2, LogOut, Plus, RefreshCw, TicketCheck, Upload } from 'lucide-react'
import { supabaseBrowser } from '@/lib/supabase/client'

type Campaign={id:string;name:string;slug:string;discount_text:string;starts_at:string;ends_at:string|null;is_active:boolean}
type Stats={total:number;available:number;assigned:number;used:number}

export default function CouponAdmin(){
 const supabase=useMemo(()=>supabaseBrowser(),[]); const [user,setUser]=useState<any>(null); const [authBusy,setAuthBusy]=useState(true); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [loginError,setLoginError]=useState(''); const [campaigns,setCampaigns]=useState<Campaign[]>([]); const [selected,setSelected]=useState<Campaign|null>(null); const [stats,setStats]=useState<Stats>({total:0,available:0,assigned:0,used:0}); const [codes,setCodes]=useState(''); const [name,setName]=useState('September 10% Campaign'); const [slug,setSlug]=useState('september-10'); const [discount,setDiscount]=useState('10% OFF'); const [ends,setEnds]=useState('2026-09-30T23:59'); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState(''); const [err,setErr]=useState(''); const [redeem,setRedeem]=useState(''); const [redeemResult,setRedeemResult]=useState('')
 useEffect(()=>{supabase.auth.getUser().then(({data})=>{setUser(data.user??null);setAuthBusy(false)});const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user??null));return()=>l.subscription.unsubscribe()},[supabase])
 useEffect(()=>{if(user)load()},[user])
 async function load(){setErr('');const {data,error}=await supabase.from('coupon_campaigns').select('*').order('created_at',{ascending:false});if(error){setErr(error.message);return}setCampaigns(data||[]);if(!selected&&data?.[0])setSelected(data[0]);else if(selected){const fresh=(data||[]).find((x:any)=>x.id===selected.id);if(fresh)setSelected(fresh)}}
 useEffect(()=>{if(selected)loadStats(selected.id)},[selected])
 async function loadStats(id:string){const {data,error}=await supabase.from('coupons').select('status').eq('campaign_id',id);if(error){setErr(error.message);return}const rows=data||[];setStats({total:rows.length,available:rows.filter((r:any)=>r.status==='available').length,assigned:rows.filter((r:any)=>r.status==='assigned').length,used:rows.filter((r:any)=>r.status==='used').length})}
 async function login(e:FormEvent){e.preventDefault();setLoginError('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setLoginError(error.message)}
 async function createCampaign(e:FormEvent){e.preventDefault();setBusy(true);setMsg('');setErr('');const {data,error}=await supabase.from('coupon_campaigns').insert({name,slug:slug.trim().toLowerCase(),discount_text:discount,ends_at:ends?new Date(ends).toISOString():null}).select().single();if(error)setErr(error.message);else{setMsg('Campaign created.');setSelected(data);await load()}setBusy(false)}
 async function importCodes(){if(!selected){setErr('Create or select a campaign first.');return}const list=Array.from(new Set(codes.split(/[\n,;]+/).map(x=>x.trim()).filter(Boolean)));if(!list.length){setErr('Paste at least one coupon code.');return}setBusy(true);setErr('');setMsg('');const rows=list.map(code=>({campaign_id:selected.id,code,status:'available'}));const {error}=await supabase.from('coupons').upsert(rows,{onConflict:'code',ignoreDuplicates:true});if(error)setErr(error.message);else{setMsg(`${list.length} code(s) imported.`);setCodes('');await loadStats(selected.id)}setBusy(false)}
 async function redeemCoupon(){setBusy(true);setRedeemResult('');const {data,error}=await supabase.rpc('redeem_coupon',{p_code:redeem});setBusy(false);if(error){setRedeemResult(error.message);return}const row=Array.isArray(data)?data[0]:data;setRedeemResult(row?.message||'Done');if(selected)loadStats(selected.id)}
 if(authBusy)return <div className="min-h-screen flex items-center justify-center">Loading…</div>
 if(!user)return <main className="min-h-screen flex items-center justify-center px-5 bg-[var(--bg)]"><form onSubmit={login} className="w-full max-w-sm rounded-3xl border hairline bg-[var(--panel)] p-7"><div className="w-12 h-12 rounded-xl bg-[var(--fg)] text-[var(--bg)] flex items-center justify-center"><Gift/></div><h1 className="text-2xl font-bold mt-5">Coupon Admin</h1><p className="text-sm text-[var(--muted)] mt-2">Sign in with an authorized IVISION account.</p><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" className="mt-6 w-full rounded-xl border hairline bg-[var(--bg)] px-4 py-3" required/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" className="mt-3 w-full rounded-xl border hairline bg-[var(--bg)] px-4 py-3" required/><button className="mt-4 w-full rounded-xl bg-[var(--fg)] text-[var(--bg)] py-3 font-semibold">Sign in</button>{loginError&&<p className="text-sm text-red-600 mt-3">{loginError}</p>}</form></main>
 return <main className="min-h-screen bg-[var(--bg)] text-[var(--fg)] px-5 py-8 md:px-8"><div className="max-w-6xl mx-auto"><header className="flex flex-wrap justify-between gap-4 items-center"><div><p className="text-xs tracking-[.2em] uppercase text-[var(--accent)]">IVISION STORES</p><h1 className="text-3xl md:text-4xl font-bold mt-2">Coupon Management</h1></div><button onClick={()=>supabase.auth.signOut()} className="inline-flex gap-2 items-center text-sm border hairline rounded-xl px-4 py-2"><LogOut size={16}/>Sign out</button></header>
 <div className="grid lg:grid-cols-[1fr_1.2fr] gap-5 mt-8"><section className="rounded-3xl border hairline bg-[var(--panel)] p-6"><h2 className="font-semibold text-lg">Create campaign</h2><input value={name} onChange={e=>setName(e.target.value)} placeholder="Campaign name" className="mt-4 w-full rounded-xl border hairline bg-[var(--bg)] px-4 py-3"/><input value={slug} onChange={e=>setSlug(e.target.value)} placeholder="slug" className="mt-3 w-full rounded-xl border hairline bg-[var(--bg)] px-4 py-3"/><input value={discount} onChange={e=>setDiscount(e.target.value)} placeholder="10% OFF" className="mt-3 w-full rounded-xl border hairline bg-[var(--bg)] px-4 py-3"/><input type="datetime-local" value={ends} onChange={e=>setEnds(e.target.value)} className="mt-3 w-full rounded-xl border hairline bg-[var(--bg)] px-4 py-3"/><button disabled={busy} onClick={createCampaign} className="mt-4 w-full rounded-xl bg-[var(--fg)] text-[var(--bg)] py-3 font-semibold flex justify-center gap-2"><Plus size={17}/>Create campaign</button></section>
 <section className="rounded-3xl border hairline bg-[var(--panel)] p-6"><div className="flex justify-between items-center"><h2 className="font-semibold text-lg">Campaigns</h2><button onClick={load} className="p-2 rounded-lg border hairline"><RefreshCw size={16}/></button></div><div className="mt-4 grid gap-2">{campaigns.map(c=><button key={c.id} onClick={()=>setSelected(c)} className={`text-left rounded-xl border hairline p-4 ${selected?.id===c.id?'ring-2 ring-[var(--accent)]':''}`}><div className="font-semibold">{c.name}</div><div className="text-xs text-[var(--muted)] mt-1">/{c.slug} · {c.discount_text} · {c.is_active?'Active':'Inactive'}</div></button>)}{!campaigns.length&&<p className="text-sm text-[var(--muted)]">No campaigns yet.</p>}</div></section></div>
 {selected&&<><section className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-5">{[['Total',stats.total],['Available',stats.available],['Claimed',stats.assigned],['Used',stats.used]].map(([a,b])=><div key={String(a)} className="rounded-2xl border hairline bg-[var(--panel)] p-5"><div className="text-xs text-[var(--muted)]">{a}</div><div className="text-3xl font-bold mt-2">{b}</div></div>)}</section><section className="grid lg:grid-cols-2 gap-5 mt-5"><div className="rounded-3xl border hairline bg-[var(--panel)] p-6"><h2 className="font-semibold text-lg flex gap-2 items-center"><Upload size={18}/>Import coupon codes</h2><p className="text-sm text-[var(--muted)] mt-2">Paste one code per line, or comma-separated. Duplicate codes are ignored.</p><textarea value={codes} onChange={e=>setCodes(e.target.value)} placeholder={'IV-001-A7K\nIV-002-X92\nIV-003-P41'} className="mt-4 w-full min-h-44 rounded-xl border hairline bg-[var(--bg)] px-4 py-3 font-mono text-sm"/><button disabled={busy} onClick={importCodes} className="mt-3 w-full rounded-xl bg-[var(--fg)] text-[var(--bg)] py-3 font-semibold">Import codes</button></div><div className="rounded-3xl border hairline bg-[var(--panel)] p-6"><h2 className="font-semibold text-lg flex gap-2 items-center"><TicketCheck size={18}/>Redeem / verify coupon</h2><p className="text-sm text-[var(--muted)] mt-2">Use this at checkout. A successful redemption permanently marks the coupon as used.</p><input value={redeem} onChange={e=>setRedeem(e.target.value)} placeholder="Enter coupon code" className="mt-5 w-full rounded-xl border hairline bg-[var(--bg)] px-4 py-3 uppercase"/><button disabled={busy||!redeem.trim()} onClick={redeemCoupon} className="mt-3 w-full rounded-xl bg-[var(--fg)] text-[var(--bg)] py-3 font-semibold">Check & redeem</button>{redeemResult&&<div className="mt-4 rounded-xl border hairline p-4 text-sm">{redeemResult}</div>}<p className="mt-5 text-xs text-[var(--muted)]">Customer link: <span className="font-mono">/coupon?campaign={selected.slug}</span></p></div></section></>}
 {msg&&<div className="fixed bottom-5 right-5 rounded-xl bg-[var(--fg)] text-[var(--bg)] px-4 py-3 text-sm">{msg}</div>}{err&&<div className="fixed bottom-5 left-5 rounded-xl bg-red-600 text-white px-4 py-3 text-sm max-w-sm">{err}</div>}
 </div></main>
}
